# Site Settings
title: "Agentic AI Talk"
description: "Understanding Agentic AI and Subagents - Exploring Perplexity Comet and Claude Code for the Web"
author: "Digital Humanities Initiative"

# GitHub Pages Settings
theme: jekyll-theme-cayman
repository: anast/AgentAI

# Build Settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Plugin Configuration
relative_links:
  enabled: true
  collections: false

optional_front_matter:
  remove_originals: false

titles_from_headings:
  enabled: true
  strip_title: false
  collections: false

# Default Front Matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - .idea/
